on:
  push:
    branches: [System]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: A3N Git Configuration
        run: |
            git config --global user.name "[A3N]"
            git config --global user.email "arancia3networkserviceprovider@a3services.local"
            git add .
            git diff --staged --quiet || git commit -m "Arancia 3 Technologies just pushed."
            git push || echo "Here."