name: A3N
  on:
    jobs:
      runs-on: ubuntu-latest
      uses: actions/checkout@v4
      steps:
        - name: Making blash
          run: make
        - name: Arancia 3 Network Service Provider Test
          run: |
            git config --global user.email "arancia3networkserviceprovider@a3services.local"
            git config --global user.name "Arancia 3 Network Service Provider [TEST]"
            git add .
            git commit -m "Aoo!"
            git push